Repository sidebase/nuxt-auth, pull requests merged in 2024-04, with the labels that each got.

#667 fix (refresh-token): handle error in refresh-token plugin and fix reshOnlyToken type
  docs/content/2.configuration/2.nuxt-config.md
  src/runtime/plugins/refresh-token.server.ts
  src/runtime/types.ts
Labels: p4, bug

#610 Feature: Option to remove server side auth
  .github/workflows/ci.yaml
  docs/content/1.getting-started/4.caching-content.md
  docs/content/1.getting-started/5.getting-help.md
  docs/content/2.configuration/2.nuxt-config.md
  docs/content/2.configuration/3.route-config.md
  docs/content/2.configuration/4.nuxt-auth-handler.md
  playground-authjs/nuxt.config.ts
  playground-authjs/pages/index.vue
  playground-authjs/pages/with-caching.vue
  playground-local/nuxt.config.ts
  playground-local/pages/index.vue
  playground-local/pages/with-caching.vue
  playground-refresh/nuxt.config.ts
  playground-refresh/pages/index.vue
  playground-refresh/pages/with-caching.vue
  src/module.ts
  src/runtime/composables/local/useAuth.ts
  src/runtime/composables/local/useAuthState.ts
  src/runtime/plugin.ts
  src/runtime/types.ts
  src/runtime/utils/kit.ts
  src/runtime/utils/local.ts
Labels: p3, enhancement

#739 docs: Added documentation for automatic session refresh
  docs/content/2.configuration/2.nuxt-config.md
  docs/content/3.application-side/2.session-access-and-management.md
Labels: documentation

#736 feat: Add cookie domain config
  docs/content/2.configuration/2.nuxt-config.md
  src/module.ts
  src/runtime/composables/local/useAuthState.ts
  src/runtime/composables/refresh/useAuthState.ts
  src/runtime/types.ts
Labels: p2, enhancement
