Repository sidebase/nuxt-auth, pull requests merged in 2024-05, with the labels that each got.

#719 fix: opt in to `import.meta.*` properties
  src/runtime/composables/authjs/useAuth.ts
  src/runtime/utils/url.ts
Labels: enhancement

#592 [PR changes #392] feat: move pointer and sessionDataType to the SessionConfig
  docs/content/2.configuration/2.nuxt-config.md
  docs/content/3.application-side/2.session-access-and-management.md
  playground-local/nuxt.config.ts
  src/module.ts
  src/runtime/composables/local/useAuth.ts
  src/runtime/helpers.ts
  src/runtime/plugins/refresh-token.server.ts
  src/runtime/types.ts
Labels: p4, enhancement, breaking-change

#729 feat: Add support for secure attribute of local/refresh provider cookies
  docs/content/2.configuration/2.nuxt-config.md
  src/module.ts
  src/runtime/composables/local/useAuthState.ts
  src/runtime/composables/refresh/useAuthState.ts
  src/runtime/types.ts
Labels: enhancement, provider-local, provider-refresh

#755 fix: don't send sign-in options in request payload
  src/runtime/composables/local/useAuth.ts
  src/runtime/composables/refresh/useAuth.ts
Labels: bug

#715 feat: Add support for custom refresh handling
  src/runtime/plugin.ts
  src/runtime/types.ts
  src/runtime/utils/refreshHandler.ts
Labels: enhancement
